import { Controller, Get, Res } from '@nestjs/common';
import { Response } from 'express';
import { PDFDocument } from 'pdf-lib';

@Controller('notes')
export class NotesController {
  @Get('export')
  async exportPreview(@Res({ passthrough: false }) res: Response) {
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595.28, 841.89]);
    const { height } = page.getSize();

    page.drawText('BAC-EVV — Export Preview', { x: 50, y: height - 80, size: 24 });
    page.drawText('Generated by /notes/export', { x: 50, y: height - 120, size: 14 });
    page.drawText('This is a placeholder PDF. DOCX→PDF pipeline will follow.', {
      x: 50, y: height - 150, size: 12,
    });

    const bytes = await pdf.save();
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'inline; filename="preview.pdf"',
    });
    res.end(Buffer.from(bytes)); // kết thúc response
  }
}
