import { Controller, Get, Res } from '@nestjs/common';
import { Response } from 'express';
import { PDFDocument, StandardFonts } from 'pdf-lib';

@Controller('notes')
export class NotesController {
  @Get('export')
  async exportPreview(@Res({ passthrough: false }) res: Response) {
    // Create a simple 1-page A4 PDF as preview
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595.28, 841.89]); // A4 size in points
    const { height } = page.getSize();

    // Embed a standard font to avoid viewer issues
    const font = await pdf.embedFont(StandardFonts.Helvetica);

    page.drawText('BAC-EVV — Export Preview', { x: 50, y: height - 80, size: 24, font });
    page.drawText('Generated by /notes/export', { x: 50, y: height - 120, size: 14, font });
    page.drawText('This is a placeholder PDF. DOCX→PDF pipeline will follow.', {
      x: 50, y: height - 150, size: 12, font,
    });

    const bytes = await pdf.save(); // Uint8Array
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'inline; filename="preview.pdf"',
      'Content-Length': String(bytes.length),
      'Cache-Control': 'no-store',
    });

    res.status(200).end(Buffer.from(bytes)); // end the response with PDF bytes
  }
}
