import { Controller, Get, Header, StreamableFile } from '@nestjs/common';
import { PDFDocument, StandardFonts } from 'pdf-lib';

@Controller('notes')
export class NotesController {
  @Get('export')
  @Header('Content-Type', 'application/pdf')
  @Header('Content-Disposition', 'inline; filename="preview.pdf"')
  async exportPreview(): Promise<StreamableFile> {
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595.28, 841.89]); // A4
    const { height } = page.getSize();
    const font = await pdf.embedFont(StandardFonts.Helvetica);

    page.drawText('BAC-EVV — Export Preview', { x: 50, y: height - 80, size: 24, font });
    page.drawText('Generated by /notes/export', { x: 50, y: height - 120, size: 14, font });
    page.drawText('This is a placeholder PDF. DOCX→PDF pipeline will follow.', {
      x: 50, y: height - 150, size: 12, font,
    });

    const bytes = await pdf.save();                // Uint8Array
    return new StreamableFile(Buffer.from(bytes)); // Nest tự set length & stream
  }
}
