import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

@Injectable()
export class NotesService {
  async exportToPdf(): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = new PassThrough();
      const chunks: Buffer[] = [];

      doc.pipe(stream);

      doc.fontSize(26).text('BAC-EVV - Export Preview', { align: 'center' });
      doc.moveDown();
      doc.fontSize(14).text('Generated by /notes/export');
      doc.moveDown();
      doc.fontSize(12).text('This is a real PDF generated with pdfkit.', { align: 'left' });

      doc.end();

      stream.on('data', (c) => chunks.push(c));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);
    });
  }
}
