name: CI lint & format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup PNPM & Install
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Prettier format check
        run: pnpm format --check

      - name: ESLint lint
        run: pnpm lint
