# ci-ping
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.mjs"
      - "**/*.cjs"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.mjs"
      - "**/*.cjs"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/**"
