name: Test API Only

on:
  workflow_dispatch:    # luôn có nút "Run workflow"
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cài PNPM nhưng KHÔNG auto install (tránh lỗi 'cwd: undefined')
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Cài dependency rõ ràng tại root
      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Lint API
        run: pnpm lint

      - name: Typecheck API
        run: pnpm typecheck

      - name: Build API
        run: pnpm build
